### ISSUE TITLE
automatisation npm version / publish

### ISSUE THREAD

**Issue by r-hannuschka** [q2g/q2g-build#13]
automate process to publish new package and create github release version

**Comment by r-hannuschka** [comment]
@konne 

i dont create a new version now or git tag. could u test it is running ? i test this on other repo and it worked for me now. just enter in command line:

npm run pkg:publish [patch|minor|major], this should build sources, create new version, push last created tag, i read about git push --tags is not the best since it push all tags, so i chose to push only last created tag with git push origin tag. 

And after that this should create a new package on npm.

**Comment by r-hannuschka** [comment]
one word to why i could not use npm publish [patch|minor|major]. npm publish has some optional parameters, if u run npm run publish patch it try to publish the package patch. Bad thing it doesnt exists ;) Or even if it exists i dont have rights to do this. So i decide to create a own npm hook pkg:publish to do this job.

**Comment by konne** [comment]
@r-hannuschka: REOPEN: please add docu for npm run pkg:publish [patch|minor|major]
