### ISSUE TITLE
q2g-build:prod not working

### ISSUE THREAD

**Issue by thomashaenig** [q2g/q2g-build#144]
shows error minify of undefined in Terser

**Comment by r-hannuschka** [comment]
could not reproduce this

![image](https://user-images.githubusercontent.com/25415574/54347594-9486df00-4647-11e9-9341-7b3476a6af96.png)

try to remove complete node_modules directory, package-lock.json and maybe run npm cache clean --force. After that install all node_modules again maybe this helps.

**Comment by r-hannuschka** [comment]
seems to working now, closed
